alter table public.store_settings
  add column if not exists catalog_categories jsonb not null default '[]'::jsonb,
  add column if not exists delivery_rates jsonb not null default '[]'::jsonb;

create table if not exists public.delivery_rate_history (
  id bigint generated by default as identity primary key,
  governorate text not null,
  old_fee numeric(12,2),
  new_fee numeric(12,2),
  created_at timestamptz not null default now()
);

alter table public.delivery_rate_history enable row level security;

drop policy if exists "Admins read delivery history" on public.delivery_rate_history;
drop policy if exists "Admins add delivery history" on public.delivery_rate_history;
create policy "Admins read delivery history" on public.delivery_rate_history
  for select to authenticated using (public.is_admin());
create policy "Admins add delivery history" on public.delivery_rate_history
  for insert to authenticated with check (public.is_admin());

grant select, insert on public.delivery_rate_history to authenticated;
grant usage, select on sequence public.delivery_rate_history_id_seq to authenticated;

notify pgrst, 'reload schema';
